USE MASTER
GO
DROP DATABASE IF EXISTS OMS

CREATE DATABASE OMS;
GO
use OMS;

CREATE TABLE users
(
    id int IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
)